import pandas as pd
import numpy as np
import os

def engineer_features(input_path, output_path):
    print(f"Loading data from {input_path}...")
    df = pd.read_csv(input_path)
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Sort for time-series features
    df = df.sort_values(['Store ID', 'Product ID', 'Date'])
    
    print("Generating Lag Features...")
    # Group by Store and Product to ensure lags are correct
    for lag in [1, 7, 30]:
        df[f'lag_demand_{lag}'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(lag)
    
    print("Generating Rolling Averages...")
    for window in [7, 30]:
        df[f'rolling_mean_{window}'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].transform(lambda x: x.rolling(window=window).mean())
    
    print("Generating Seasonal Index...")
    # Simple seasonal index: Avg Demand of Season / Total Avg Demand
    avg_demand = df['Units Sold'].mean()
    seasonal_avg = df.groupby('Seasonality')['Units Sold'].transform('mean')
    df['seasonal_index'] = seasonal_avg / avg_demand
    
    print("Calculating Promotion Impact...")
    # dummy check for holiday/promotion
    # Assume 1 for holiday, 0 for not (already binary or categorical)
    promo_avg = df[df['Holiday/Promotion'] == 'Yes']['Units Sold'].mean()
    non_promo_avg = df[df['Holiday/Promotion'] == 'No']['Units Sold'].mean()
    df['expected_promo_uplift'] = promo_avg - non_promo_avg
    
    print("Calculating Price Elasticity...")
    # Very simplified elasticity: (dQ/Q) / (dP/P)
    # We'll calculate this per product
    def calc_elasticity(group):
        if len(group) < 2: return 0
        dq = group['Units Sold'].pct_change()
        dp = group['Price'].pct_change()
        # Avoid division by zero and handle infinity
        elasticity = dq / dp
        return elasticity.replace([np.inf, -np.inf], 0).fillna(0).mean()

    # Apply per product and map back
    elasticity_map = df.groupby('Product ID').apply(calc_elasticity)
    df['price_elasticity'] = df['Product ID'].map(elasticity_map)
    
    print("Calculating Inventory Metrics...")
    # Stock cover days: Inventory / Rolling Avg Demand (7 days)
    # Avoid div by zero
    df['stock_cover_days'] = df['Inventory Level'] / (df['rolling_mean_7'] + 0.1)
    
    # Inventory Turnover: Units Sold / Inventory Level
    df['inventory_turnover'] = df['Units Sold'] / (df['Inventory Level'] + 0.1)
    
    # Lead Time Demand: (Avg Demand) * Lead Time (Assume 7 days)
    df['lead_time_demand'] = df['rolling_mean_7'] * 7
    
    # Fill NAs generated by shifts/rolling
    df = df.fillna(0)
    
    print(f"Saving feature dataset to {output_path}...")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print("Feature engineering complete.")

if __name__ == "__main__":
    # We use the raw data for initial feature engineering to keep interpretability
    # then we'll pipe it through cleaning if needed or handle it here.
    input_file = 'data/retail_store_inventory (1).csv'
    output_file = 'processed_data/feature_engineered_inventory.csv'
    engineer_features(input_file, output_file)
